# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 20

[[main]]
  name = "Working Papers"
  url = "#working_papers"
  weight = 30

#[[main]]
#  name = "Other Research"
#  url = "#other_research"
#  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "References"
  url = "#references"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 75

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 80
